include: 'https://raw.githubusercontent.com/Nitrokey/common-ci-jobs/master/common_jobs.yml'

stages:
  - pull-github
  - deploy

variables:
  GIT_STRATEGY: clone            
  GIT_DEPTH: 0                    
  GIT_SUBMODULE_STRATEGY: recursive 
  SCRIPTS_REPO: git@git.dotplex.com:nitrokey/gitlab-ci.git
  REPO_USER: nitrokey
  REPO_NAME: debian-oem
  MAIN_BRANCH: nitropad

oem-release:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - lxc
  stage: deploy
  before_script:
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > ~/.ssh/common_scripts_key
    - echo "$COMMON_SCRIPTS_KEY" >> ~/.ssh/common_scripts_key
    - echo "-----END OPENSSH PRIVATE KEY-----" >> ~/.ssh/common_scripts_key
    - chmod 600 ~/.ssh/common_scripts_key
    - export SCRIPTS_DIR=$(mktemp -d)
    - git clone -q --depth 1 $SCRIPTS_REPO $SCRIPTS_DIR
  script:
    - make ci
    - chmod +x $SCRIPTS_DIR/ci-scripts/oem-release.sh
    - $SCRIPTS_DIR/ci-scripts/oem-release.sh *nitrokey*.iso
  after_script:
    - wget $icon_server/checkmark/$CI_COMMIT_REF_NAME/$CI_COMMIT_SHA/$CI_JOB_NAME/$CI_JOB_STATUS/${CI_JOB_URL#*/*/*/}


